import io
import pytest
import openpyxl
from create_template import create_pothys_template
from app.services.excel_engine.erp_excel_parser import ERPExcelParser
from app.services.doc_parser import document_parser

def test_parse_standard_official_template():
    """Test parsing standard Pothys Excel template generated by create_template.py."""
    create_pothys_template()
    with open("templates/pothys_report_template.xlsx", "rb") as f:
        file_bytes = f.read()

    res = document_parser.parse_pothys_excel(file_bytes)

    assert "summary" in res
    assert "employees" in res
    assert "scheme_summary" in res
    assert "diagnostics" in res

    summary = res["summary"]
    assert summary["branch_name"] == "Coimbatore Swarna Mahal"
    assert summary["gold_sales"] == 0.0
    assert summary["total_revenue"] == 0.0
    assert summary["remarks"] == "All operations running smoothly."

    employees = res["employees"]
    assert len(employees) == 3
    assert employees[0]["name"] == "Rajesh Kumar"
    assert employees[0]["gold_grams_sold"] == 12.5
    assert employees[0]["gold_amount"] == 95000.00
    assert employees[0]["digisilver_enrollments"] == 8

def test_parse_custom_shifted_template():
    """Test parsing custom template with extra rows, shifted columns, alternative headers, and renamed tabs."""
    wb = openpyxl.Workbook()

    # Sheet 1: Renamed tab, shifted metrics
    ws1 = wb.active
    ws1.title = "Daily Summary Sheet"

    # Row 1-4: Title banner & empty rows
    ws1["A2"] = "SWARNA MAHAL DAILY REPORT"

    # Row 6: Shifted metadata
    ws1["B6"] = "Report Dt"
    ws1["C6"] = "2026-07-23"
    ws1["E6"] = "Showroom"
    ws1["F6"] = "Madurai Swarna Mahal"

    # Row 10: Shifted Sales metrics
    ws1["B10"] = "Today's Gold"
    ws1["C10"] = 150000.00
    ws1["B11"] = "Today's Silver"
    ws1["C11"] = 25000.00
    ws1["B12"] = "Overall Revenue"
    ws1["C12"] = 175000.00

    # Row 15: Shifted HR & Scheme
    ws1["E10"] = "Staff Present"
    ws1["F10"] = 18
    ws1["E11"] = "Staff Absent"
    ws1["F11"] = 2

    ws1["B16"] = "Client Complaints"
    ws1["C16"] = "No issues reported"
    ws1["B17"] = "Notes"
    ws1["C17"] = "Great overall sales today."

    # Sheet 2: Staff performance with different column order
    ws2 = wb.create_sheet(title="Staff Performance")
    headers = [
        "Staff Name", "Role", "Gold Weight (g)", "Gold Sales",
        "Silver Weight", "Silver Sales", "Digi Gold Count", "Digi Silver Count"
    ]
    for c, h in enumerate(headers, start=1):
        ws2.cell(row=3, column=c, value=h)

    ws2.cell(row=4, column=1, value="Vijay Sethupathi")
    ws2.cell(row=4, column=2, value="Manager")
    ws2.cell(row=4, column=3, value=10.0)
    ws2.cell(row=4, column=4, value=80000.00)
    ws2.cell(row=4, column=5, value=50.0)
    ws2.cell(row=4, column=6, value=6000.00)
    ws2.cell(row=4, column=7, value=4)
    ws2.cell(row=4, column=8, value=6)

    stream = io.BytesIO()
    wb.save(stream)
    file_bytes = stream.getvalue()

    res = document_parser.parse_pothys_excel(file_bytes)
    summary = res["summary"]

    assert summary["branch_name"] == "Madurai Swarna Mahal"
    assert summary["gold_sales"] == 150000.00
    assert summary["silver_sales"] == 25000.00
    assert summary["total_revenue"] == 175000.00
    assert summary["employees_present"] == 18
    assert summary["customer_complaints"] == "No issues reported"

    employees = res["employees"]
    assert len(employees) == 1
    assert employees[0]["name"] == "Vijay Sethupathi"
    assert employees[0]["gold_amount"] == 80000.00
    assert employees[0]["digigold_enrollments"] == 4

def test_parse_single_sheet_combined_template():
    """Test parsing a single-sheet Excel file containing both summary and employee table."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Report"

    # Summary key-values
    ws["A1"] = "Location"
    ws["B1"] = "Trichy Swarna Mahal"
    ws["A2"] = "Gold Sales"
    ws["B2"] = 50000.00
    ws["A3"] = "Total Revenue"
    ws["B3"] = 50000.00

    # Employee table below on same sheet
    headers = ["Emp Name", "Desig", "Gold Value", "Silver Value"]
    for c, h in enumerate(headers, start=1):
        ws.cell(row=6, column=c, value=h)

    ws.cell(row=7, column=1, value="Saritha Kumar")
    ws.cell(row=7, column=2, value="Sales Executive")
    ws.cell(row=7, column=3, value=50000.00)
    ws.cell(row=7, column=4, value=0.0)

    stream = io.BytesIO()
    wb.save(stream)
    file_bytes = stream.getvalue()

    res = ERPExcelParser.parse(file_bytes)
    assert res["summary"]["branch_name"] == "Trichy Swarna Mahal"
    assert res["summary"]["gold_sales"] == 50000.00
    assert len(res["employees"]) == 1
    assert res["employees"][0]["name"] == "Saritha Kumar"

def test_parse_scheme_performance_sheet():
    """Test dynamic parsing of Scheme Performance table sheet with multiple custom schemes."""
    wb = openpyxl.Workbook()
    ws1 = wb.active
    ws1.title = "Branch Summary"
    ws1["A1"] = "Branch Name"
    ws1["B1"] = "Coimbatore Swarna Mahal"
    ws1["A2"] = "Total Revenue"
    ws1["B2"] = 2500000.00

    ws2 = wb.create_sheet(title="Scheme Performance")
    headers = ["Scheme", "Today's Enrollments", "Revenue", "Remarks"]
    for c, h in enumerate(headers, start=1):
        ws2.cell(row=2, column=c, value=h)

    schemes_data = [
        ("DigiGold", 41, 825000.0, "Great response"),
        ("DigiSilver", 29, 375000.0, "Consistent"),
        ("Premium", 18, 450000.0, "High value"),
        ("Gold Elite", 12, 600000.0, "VIP clients"),
        ("Wedding Scheme", 8, 500000.0, "Seasonal"),
        ("Festival Offer", 15, 350000.0, "Promo active")
    ]

    for r_idx, (s_name, enr, rev, rem) in enumerate(schemes_data, start=3):
        ws2.cell(row=r_idx, column=1, value=s_name)
        ws2.cell(row=r_idx, column=2, value=enr)
        ws2.cell(row=r_idx, column=3, value=rev)
        ws2.cell(row=r_idx, column=4, value=rem)

    stream = io.BytesIO()
    wb.save(stream)
    file_bytes = stream.getvalue()

    res = ERPExcelParser.parse(file_bytes)
    assert "scheme_summary" in res
    scheme_items = res["scheme_summary"]["scheme_items"]
    assert len(scheme_items) == 6

    scheme_names = [s["scheme_name"] for s in scheme_items]
    assert "DigiGold" in scheme_names
    assert "DigiSilver" in scheme_names
    assert "Premium" in scheme_names
    assert "Gold Elite" in scheme_names

    digigold = next(s for s in scheme_items if s["scheme_name"] == "DigiGold")
    assert digigold["enrollments"] == 41
    assert digigold["revenue"] == 825000.0


def test_parse_weight_and_mrp_metrics():
    """Test parsing of the official Excel template 5 business metrics (Gold, Diamond, Platinum, Silver weight, Silver MRP)."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Branch Summary"

    ws["A1"] = "Branch Name"
    ws["B1"] = "Chromepet Swarna Mahal"
    ws["A2"] = "Total Revenue"
    ws["B2"] = 2530000.00
    ws["A3"] = "Gold Weight"
    ws["B3"] = "124.5g"
    ws["A4"] = "Diamond Weight"
    ws["B4"] = "15.2 cts"
    ws["A5"] = "Platinum Weight"
    ws["B5"] = "45.0g"
    ws["A6"] = "Silver Weight"
    ws["B6"] = "850.0g"
    ws["A7"] = "Silver MRP"
    ws["B7"] = "75,000"

    stream = io.BytesIO()
    wb.save(stream)
    file_bytes = stream.getvalue()

    res = ERPExcelParser.parse(file_bytes)
    summary = res["summary"]

    assert summary["branch_name"] == "Chromepet Swarna Mahal"
    assert summary["total_revenue"] == 2530000.00
    assert summary["gold_weight"] == "124.5g"
    assert summary["diamond_weight"] == "15.2 cts"
    assert summary["platinum_weight"] == "45.0g"
    assert summary["silver_weight"] == "850.0g"
    assert summary["silver_mrp"] == "75,000"


